<Project>
  <PropertyGroup>
    <AssemblyName>pyRevitLabs.PyRevit</AssemblyName>
    <IntermediateOutputPath>obj\Release\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>C:\Users\ccrosley\github\pyRevit-fork\dev\pyRevitLabs\pyRevitLabs.PyRevit\obj\</MSBuildProjectExtensionsPath>
    <_TargetAssemblyProjectName>pyRevitLabs.PyRevit</_TargetAssemblyProjectName>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nett" Version="0.15.0" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'" Include="MadMilkman.Ini" Version="1.0.6" />
    <PackageReference Condition="'$(TargetFrameworkIdentifier)' == '.NetCoreApp'" Include="MadMilkman.Ini.Unofficial" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\pyRevitLabs.Common\pyRevitLabs.Common.csproj" />
    <ProjectReference Include="..\pyRevitLabs.CommonWPF\pyRevitLabs.CommonWPF.csproj" />
    <ProjectReference Include="..\pyRevitLabs.TargetApps.Revit\pyRevitLabs.TargetApps.Revit.csproj" />
  </ItemGroup>
  <Target Name="DeployDependencies" AfterTargets="Deploy">
    <Copy SourceFiles="$(OutDir)\Nett.dll" DestinationFolder="$(PyRevitBinDir)" />
  </Target>
  <ItemGroup>
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\dotnetversionfinder\2.1.1\lib\net45\DotNetVersionFinder.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\libgit2sharp\0.31.0\lib\net472\LibGit2Sharp.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\madmilkman.ini\1.0.6\lib\net20\MadMilkman.Ini.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\microsoft.bcl.hashcode\6.0.0\lib\net462\Microsoft.Bcl.HashCode.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\microsoft.codeanalysis.csharp\4.11.0\lib\netstandard2.0\Microsoft.CodeAnalysis.CSharp.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\microsoft.codeanalysis.common\4.11.0\lib\netstandard2.0\Microsoft.CodeAnalysis.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\microsoft.codeanalysis.visualbasic\4.11.0\lib\netstandard2.0\Microsoft.CodeAnalysis.VisualBasic.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\Microsoft.CSharp.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\mscorlib.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\nett\0.15.0\lib\net40\Nett.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\openmcdf\3.1.2\lib\netstandard2.0\OpenMcdf.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\PresentationCore.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\PresentationFramework.dll" />
    <ReferencePath Include="C:\Users\ccrosley\github\pyRevit-fork\dev\pyRevitLabs\pyRevitLabs.Common\bin\Release\net48\pyRevitLabs.Common.dll" />
    <ReferencePath Include="C:\Users\ccrosley\github\pyRevit-fork\dev\pyRevitLabs\pyRevitLabs.CommonWPF\bin\Release\net48\pyRevitLabs.CommonWPF.dll" />
    <ReferencePath Include="C:\Users\ccrosley\github\pyRevit-fork\dev\libs\netfx\pyRevitLabs.Json.dll" />
    <ReferencePath Include="C:\Users\ccrosley\github\pyRevit-fork\dev\libs\netfx\pyRevitLabs.MahAppsMetro.dll" />
    <ReferencePath Include="C:\Users\ccrosley\github\pyRevit-fork\dev\libs\netfx\pyRevitLabs.NLog.dll" />
    <ReferencePath Include="C:\Users\ccrosley\github\pyRevit-fork\dev\pyRevitLabs\pyRevitLabs.TargetApps.Revit\bin\Release\net48\pyRevitLabs.TargetApps.Revit.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\system.buffers\4.6.0\lib\net462\System.Buffers.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\system.collections.immutable\8.0.0\lib\net462\System.Collections.Immutable.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Core.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Data.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Drawing.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.IO.Compression.FileSystem.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\system.memory\4.6.0\lib\net462\System.Memory.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Numerics.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\system.numerics.vectors\4.6.0\lib\net462\System.Numerics.Vectors.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\system.reflection.metadata\8.0.0\lib\net462\System.Reflection.Metadata.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\system.runtime.compilerservices.unsafe\6.1.0\lib\net462\System.Runtime.CompilerServices.Unsafe.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Runtime.Serialization.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\system.text.encoding.codepages\7.0.0\lib\net462\System.Text.Encoding.CodePages.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\system.threading.tasks.extensions\4.5.4\lib\net461\System.Threading.Tasks.Extensions.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Windows.Controls.Ribbon.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Windows.Forms.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Xaml.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Xml.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Xml.Linq.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\UIAutomationClient.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\UIAutomationClientsideProviders.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\UIAutomationProvider.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\UIAutomationTypes.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\WindowsBase.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\WindowsFormsIntegration.dll" />
    <ReferencePath Include="C:\Users\ccrosley\.nuget\packages\yamldotnet\16.3.0\lib\net47\YamlDotNet.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\Facades\netstandard.dll" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="C:\Users\ccrosley\.nuget\packages\microsoft.codeanalysis.analyzers\3.3.4\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll" />
    <Analyzer Include="C:\Users\ccrosley\.nuget\packages\microsoft.codeanalysis.analyzers\3.3.4\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>