<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>pyRevitLabs.UI.Protocol</AssemblyName>
    <RootNamespace>PyRevitLabs.UI.Protocol</RootNamespace>
  </PropertyGroup>
</Project>
